/**
 * Catalog of every TTS prompt that ships in the Asterisk
 * `core-sounds-es` pack, retargeted to **neutral Mexican Spanish**
 * (Spanish-MX, central CDMX register) and cleaned up against the
 * issues we found in the canonical 1.6.1 manifesto:
 *
 *   - missing diacritics ("manana" -> "mañana", "contrasena" -> "contraseña",
 *     "numero" -> "número", "telefono" -> "teléfono", ...)
 *   - obvious typos in core-sounds-es.txt (e.g. duplicate `digits/0`,
 *     "ingese", "introdusca", "nimbre", "entidade", "defeto",
 *     "contrasenia", "atravez", ...)
 *   - europeanisms / awkward translations swapped for the wording a
 *     Mexican IVR actually uses ("tecla de número" -> "almohadilla",
 *     "asterisco" stays, "guion" -> "guion" but pronounced naturally,
 *     "tono ascendente" instead of "[ascending tones]", ...)
 *
 * Each entry maps to one output file under the same relative path the
 * official pack uses, so the resulting tarball is a drop-in
 * replacement for `asterisk-core-sounds-es-<codec>` and works with
 * every existing dialplan / ARI playback URI (`digits:N`, `number:N`,
 * `vm-*`, ...).
 *
 * Lines whose `text` is an empty string represent prompts the official
 * pack also ships empty (`dir-usingkeypad`, `dir-welcome`); they're
 * skipped at build time.
 *
 * ~485 TTS items. Pure-tone files (beep, ascending-2tone, ...) and
 * `silence/N` are NOT here; see `passthrough.ts`.
 */

export interface CatalogItem {
  /** Path inside the sound pack, without extension. */
  path: string;
  /** Spanish-MX text. Empty string => skip (pack ships an empty file). */
  text: string;
  /**
   * Optional override hints embedded in the text *for the TTS model*
   * only (audio tags like [calmly], [serious], etc.). Most items use
   * the catalog-wide default delivery defined in `prompt.ts`.
   */
  tag?: string;
}

const tail = '[neutral, falling intonation]';

/**
 * Helper: a "reading-style" entry. The default style for IVR prompts
 * is calm, professional, slightly falling intonation at the end so the
 * file mixes well in the middle of a sentence (mirrors how Allison
 * recorded the official EN pack).
 */
const ivr = (path: string, text: string): CatalogItem => ({ path, text });

export const CATALOG: CatalogItem[] = [
  // ─────────────────────────────── agent-* ───────────────────────────────
  ivr('agent-alreadyon',
    'Ese agente ya ha sido autenticado. Por favor ingrese su número de agente seguido por la tecla de almohadilla.'),
  ivr('agent-incorrect',
    'Clave incorrecta. Por favor, ingrese su número de agente seguido por la tecla de almohadilla.'),
  ivr('agent-loggedoff', 'Agente desconectado.'),
  ivr('agent-loginok', 'Agente conectado.'),
  ivr('agent-newlocation',
    'Por favor ingrese una nueva extensión seguida por la tecla de almohadilla.'),
  ivr('agent-pass',
    'Por favor ingrese su contraseña seguida por la tecla de almohadilla.'),
  ivr('agent-user',
    'Autenticación de agente. Por favor ingrese su número de agente seguido por la tecla de almohadilla.'),

  // ─────────────────────────────── auth-* ────────────────────────────────
  ivr('auth-incorrect',
    'Contraseña incorrecta. Por favor ingrese su contraseña seguida por la tecla de almohadilla.'),
  ivr('auth-thankyou', 'Gracias.'),

  // ─────────────────────────────── conf-* ────────────────────────────────
  ivr('conf-adminmenu-162',
    'Por favor presione uno para activar o desactivar el modo de silencio. Dos para activar o desactivar el candado en la conferencia. Tres para expulsar al último usuario. Cuatro o seis para subir o bajar el volumen de la conferencia. Cinco para extender la conferencia. Siete o nueve para bajar o subir su propio volumen. U ocho para salir.'),
  ivr('conf-adminmenu-18',
    'Por favor presione uno para activar o desactivar el modo silencio personal. Dos para bloquear o desbloquear la conferencia. Tres para expulsar al último usuario. Cuatro o seis para disminuir o incrementar el volumen de la conferencia. Cinco para extender la conferencia. Siete o nueve para disminuir o incrementar su volumen. U ocho para más opciones.'),
  ivr('conf-adminmenu-menu8',
    'Presione uno para listar los usuarios de la conferencia. Dos para expulsar a todos los usuarios que no son administradores. Tres para activar o desactivar el modo silencio para todos los usuarios que no son administradores. Cuatro para grabar esta conferencia. U ocho para salir de este menú y regresar a la conferencia.'),
  ivr('conf-adminmenu',
    'Por favor marque uno para habilitar o deshabilitar el modo silencio. Dos para bloquear o desbloquear la conferencia. Tres para expulsar al último usuario. Cuatro o seis para aumentar o disminuir el volumen de la conferencia. Siete o nueve para su propio volumen. U ocho para salir.'),
  ivr('conf-enteringno', 'Entrando a la conferencia número'),
  ivr('conf-errormenu', 'Opción inválida.'),
  ivr('conf-extended', 'La conferencia ha sido extendida.'),
  ivr('conf-getchannel',
    'Por favor ingrese el número de canal seguido por la tecla de almohadilla.'),
  ivr('conf-getconfno',
    'Por favor ingrese el número de la conferencia seguido por la tecla de almohadilla.'),
  ivr('conf-getpin',
    'Por favor ingrese la clave de entrada para la conferencia.'),
  ivr('conf-hasjoin', 'Ya está en la conferencia.'),
  ivr('conf-hasleft', 'Ha dejado la conferencia.'),
  ivr('conf-invalid',
    'Número de conferencia inválido. Por favor intente de nuevo.'),
  ivr('conf-invalidpin',
    'Clave de entrada inválida para esta conferencia.'),
  ivr('conf-kicked',
    'Ha sido expulsado del sistema y de esta conferencia.'),
  ivr('conf-leaderhasleft', 'El líder ha dejado la conferencia.'),
  ivr('conf-locked', 'La conferencia ha sido bloqueada.'),
  ivr('conf-lockednow', 'La conferencia ha sido bloqueada.'),
  ivr('conf-muted', 'Está usted ahora en modo silencio.'),
  ivr('conf-noempty', 'Por el momento no hay conferencias vacías.'),
  ivr('conf-nonextended', 'La conferencia no puede ser extendida.'),
  ivr('conf-now-muted', 'La conferencia está ahora en modo silencio.'),
  ivr('conf-now-recording', 'La conferencia está siendo grabada.'),
  ivr('conf-now-unmuted',
    'El modo silencio ha sido desactivado en la conferencia.'),
  ivr('conf-onlyone',
    'Actualmente solo hay otro participante en la conferencia.'),
  ivr('conf-onlyperson',
    'Por el momento, usted es la única persona en la conferencia.'),
  ivr('conf-otherinparty', 'Otros participantes en la conferencia.'),
  ivr('conf-placeintoconf', 'Usted se unirá a la conferencia.'),
  ivr('conf-roll-callcomplete', 'Lista de llamadas completa.'),
  ivr('conf-thereare', 'Actualmente hay'),
  ivr('conf-unlockednow', 'La conferencia ha sido desbloqueada.'),
  ivr('conf-unmuted', 'Ha desactivado el modo silencio.'),
  ivr('conf-usermenu-162',
    'Por favor presione uno para activar o desactivar el modo silencio personal. Cuatro o seis para disminuir o incrementar el volumen de la conferencia. Cinco para extender la conferencia. Siete o nueve para disminuir o incrementar su volumen. U ocho para salir de este menú y regresar a la conferencia.'),
  ivr('conf-usermenu',
    'Por favor marque uno para habilitar o deshabilitar el modo silencio. Cuatro o seis para aumentar o disminuir el volumen de la conferencia. Siete o nueve para su propio volumen. U ocho para salir.'),
  ivr('conf-userswilljoin', 'Usuarios se unirán a la conferencia.'),
  ivr('conf-userwilljoin', 'Usuario se unirá a la conferencia.'),
  ivr('conf-waitforleader',
    'La conferencia comenzará cuando llegue el líder.'),

  // ───────────────────────────── confbridge-* ────────────────────────────
  ivr('confbridge-begin-glorious-a',
    'La conferencia iniciará cuando nuestro glorioso líder llegue.'),
  ivr('confbridge-begin-glorious-b',
    'La conferencia iniciará cuando nuestro glorioso líder llegue.'),
  ivr('confbridge-begin-glorious-c',
    'La conferencia iniciará cuando nuestro glorioso líder llegue.'),
  ivr('confbridge-conf-begin', 'La conferencia iniciará ahora.'),
  ivr('confbridge-conf-end', 'La conferencia ha terminado.'),
  ivr('confbridge-dec-list-vol-in',
    'Para reducir el volumen del audio de otros participantes...'),
  ivr('confbridge-dec-list-vol-out',
    '...para reducir el volumen del audio de otros participantes.'),
  ivr('confbridge-dec-talk-vol-in',
    'Para reducir el volumen de su voz hacia otros participantes...'),
  ivr('confbridge-dec-talk-vol-out',
    '...para reducir el volumen de su voz hacia otros participantes.'),
  ivr('confbridge-has-joined', '...ha ingresado a la conferencia.'),
  ivr('confbridge-has-left', '...ha dejado la conferencia.'),
  ivr('confbridge-inc-list-vol-in',
    'Para aumentar el volumen del audio de otros participantes...'),
  ivr('confbridge-inc-list-vol-out',
    '...para aumentar el volumen del audio de otros participantes.'),
  ivr('confbridge-inc-talk-vol-in',
    'Para aumentar el volumen de su voz hacia otros participantes...'),
  ivr('confbridge-inc-talk-vol-out',
    '...para aumentar el volumen de su voz hacia otros participantes.'),
  ivr('confbridge-invalid', 'Usted ha ingresado una opción inválida.'),
  ivr('confbridge-leave-in', 'Para salir de la conferencia...'),
  ivr('confbridge-leave-out', '...para salir de la conferencia.'),
  ivr('confbridge-leave',
    'Para salir de la conferencia presione la tecla indicada.'),
  ivr('confbridge-lock-extended',
    '...para bloquear o desbloquear la conferencia. Cuando una conferencia está bloqueada, solo los administradores pueden entrar.'),
  ivr('confbridge-lock-in', 'Para bloquear o desbloquear la conferencia...'),
  ivr('confbridge-lock-no-join',
    'La conferencia está actualmente bloqueada y no se puede ingresar.'),
  ivr('confbridge-lock-out',
    '...para bloquear o desbloquear la conferencia.'),
  ivr('confbridge-locked', 'La conferencia está ahora bloqueada.'),
  ivr('confbridge-menu-exit-in', 'Para salir del menú...'),
  ivr('confbridge-menu-exit-out', '...para salir del menú.'),
  ivr('confbridge-mute-extended',
    '...para activar o desactivar el modo silencio. En modo silencio no puede enviar audio a otros participantes; sin embargo aún escuchará el audio de los otros participantes que no estén en modo silencio.'),
  ivr('confbridge-mute-in',
    'Para activar o desactivar el modo silencio...'),
  ivr('confbridge-mute-out',
    '...para activar o desactivar el modo silencio.'),
  ivr('confbridge-muted', 'Usted se encuentra ahora en modo silencio.'),
  ivr('confbridge-only-one',
    'Actualmente hay otro participante en la conferencia.'),
  ivr('confbridge-only-participant',
    'Usted es actualmente el único participante en la conferencia.'),
  ivr('confbridge-participants', '...participantes en la conferencia.'),
  ivr('confbridge-pin-bad',
    'Usted ha introducido demasiados números de identificación personal inválidos.'),
  ivr('confbridge-pin',
    'Por favor ingrese su número de identificación personal seguido de la tecla de almohadilla.'),
  ivr('confbridge-remove-last-in',
    'Para expulsar al participante ingresado más recientemente en la conferencia...'),
  ivr('confbridge-remove-last-out',
    '...para expulsar al participante ingresado más recientemente en la conferencia.'),
  ivr('confbridge-removed',
    'Usted ha sido expulsado de la conferencia.'),
  ivr('confbridge-rest-list-vol-in',
    'Para reiniciar el volumen del audio de la conferencia al nivel por defecto...'),
  ivr('confbridge-rest-list-vol-out',
    '...para reiniciar el volumen del audio de la conferencia al nivel por defecto.'),
  ivr('confbridge-rest-talk-vol-in',
    'Para reiniciar el volumen de su voz al nivel por defecto...'),
  ivr('confbridge-rest-talk-vol-out',
    '...para reiniciar el volumen de su voz al nivel por defecto.'),
  ivr('confbridge-there-are', 'Hay actualmente...'),
  ivr('confbridge-unlocked', 'La conferencia está ahora desbloqueada.'),
  ivr('confbridge-unmuted',
    'Usted ya no se encuentra en modo silencio.'),

  // ─────────────────────────────── demo-* ────────────────────────────────
  ivr('demo-abouttotry',
    'Intentaré establecer una conexión IAX con un servidor de demostración localizado en Digium. Para lograr esto, usted ya debe estar conectado a Internet. Por favor espere mientras intento establecer la conexión.'),
  ivr('demo-congrats',
    'Felicidades, usted ha instalado y ejecutado exitosamente su PBX de código abierto, Asterisk. También ha instalado una serie de sonidos y archivos de configuración que le ayudarán a comenzar. Al igual que una PBX normal, usted navegará esta demostración tecleando dígitos en su teléfono. Si está usando el canal de consola en lugar de un teléfono físico, puede usar los comandos "dial", "answer" y "hangup" para simular su teléfono.'),
  ivr('demo-echodone', 'La prueba del eco ha sido completada.'),
  ivr('demo-echotest',
    'Está a punto de entrar a la prueba de eco. En este modo, todo lo que diga será repetido tan pronto como sea recibido por el sistema. El propósito de esta prueba es darle una idea de la demora del sonido entre usted y el sistema ejecutando la prueba. Para terminar, cuelgue o presione la tecla de almohadilla.'),
  ivr('demo-enterkeywords',
    'Por favor ingrese una o más palabras clave separadas por un asterisco y después presione la tecla de almohadilla.'),
  ivr('demo-instruct',
    'Si usted desea obtener más información técnica sobre Asterisk, marque dos ahora. Si quiere probar la capacidad de voz sobre IP de Asterisk, marque quinientos para intentar una conexión IAX a un servidor de demostración en Digium. Para que funcione esta prueba, usted ya tiene que estar conectado a Internet. Para ejecutar una prueba de eco, marque seiscientos. La configuración demuestra también tener un solo usuario con la extensión mil doscientos treinta y cuatro y la contraseña cuatro mil doscientos cuarenta y dos. Ese usuario está configurado para llamar a la consola cuando se ha marcado su extensión.'),
  ivr('demo-moreinfo',
    'Asterisk es una plataforma PBX e IVR de código abierto que corre en el sistema operativo Linux. Para más información, visite www.asterisk.org'),
  ivr('demo-nogo',
    'Lo siento, pero no fue posible crear la conexión al servidor de demostración en Digium. Puede encontrar información útil para solucionar el problema en la consola de Asterisk.'),
  ivr('demo-nomatch',
    'Lo siento, pero no hay una correspondencia con esas palabras clave.'),
  ivr('demo-thanks',
    'Hasta luego. Gracias por probar Asterisk, la PBX de código abierto.'),

  // ───────────────────────────── dictate/* ───────────────────────────────
  ivr('dictate/both_help',
    'Presione el asterisco para pausar o continuar. Presione la tecla de almohadilla para entrar a un nuevo archivo de dictado.'),
  ivr('dictate/enter_filename',
    'Introduzca el nombre numérico del archivo de dictado seguido por la tecla de almohadilla, o presione la tecla de almohadilla para salir.'),
  ivr('dictate/forhelp', 'Marque cero para obtener ayuda.'),
  ivr('dictate/pause', 'pausa'),
  ivr('dictate/paused', 'pausado'),
  ivr('dictate/play_help',
    'Marque uno para cambiar al modo de grabación. Dos para reproducir rápidamente. Siete para saltar hacia atrás. Ocho para saltar hacia adelante.'),
  ivr('dictate/playback', 'reproducción'),
  ivr('dictate/playback_mode', 'Modo de reproducción.'),
  ivr('dictate/record', 'grabar'),
  ivr('dictate/record_help',
    'Marque uno para cambiar a modo de reproducción. Ocho para borrar el archivo y comenzar de nuevo.'),
  ivr('dictate/record_mode', 'Modo de grabación.'),
  ivr('dictate/truncating_audio', 'borrando audio'),

  // ─────────────────────────────── digits/* ──────────────────────────────
  // Numbers 0-9 (masculine, default for SayDigits/SayNumber).
  ivr('digits/0', 'cero'),
  ivr('digits/1', 'uno'),
  ivr('digits/2', 'dos'),
  ivr('digits/3', 'tres'),
  ivr('digits/4', 'cuatro'),
  ivr('digits/5', 'cinco'),
  ivr('digits/6', 'seis'),
  ivr('digits/7', 'siete'),
  ivr('digits/8', 'ocho'),
  ivr('digits/9', 'nueve'),
  // Apocopated/feminine variants used by SayNumber.
  ivr('digits/1F', 'una'),
  ivr('digits/1M', 'un'),
  // Tens 10-29 individual.
  ivr('digits/10', 'diez'),
  ivr('digits/11', 'once'),
  ivr('digits/12', 'doce'),
  ivr('digits/13', 'trece'),
  ivr('digits/14', 'catorce'),
  ivr('digits/15', 'quince'),
  ivr('digits/16', 'dieciséis'),
  ivr('digits/17', 'diecisiete'),
  ivr('digits/18', 'dieciocho'),
  ivr('digits/19', 'diecinueve'),
  ivr('digits/20', 'veinte'),
  ivr('digits/20-and', 'veinti'),
  ivr('digits/21', 'veintiuno'),
  ivr('digits/21-and', 'veintiún'),
  ivr('digits/22', 'veintidós'),
  ivr('digits/23', 'veintitrés'),
  ivr('digits/24', 'veinticuatro'),
  ivr('digits/25', 'veinticinco'),
  ivr('digits/26', 'veintiséis'),
  ivr('digits/27', 'veintisiete'),
  ivr('digits/28', 'veintiocho'),
  ivr('digits/29', 'veintinueve'),
  // Tens 30-90.
  ivr('digits/30', 'treinta'),
  ivr('digits/40', 'cuarenta'),
  ivr('digits/50', 'cincuenta'),
  ivr('digits/60', 'sesenta'),
  ivr('digits/70', 'setenta'),
  ivr('digits/80', 'ochenta'),
  ivr('digits/90', 'noventa'),
  // Hundreds.
  ivr('digits/100-and', 'ciento'),
  ivr('digits/200', 'doscientos'),
  ivr('digits/300', 'trescientos'),
  ivr('digits/400', 'cuatrocientos'),
  ivr('digits/500', 'quinientos'),
  ivr('digits/600', 'seiscientos'),
  ivr('digits/700', 'setecientos'),
  ivr('digits/800', 'ochocientos'),
  ivr('digits/900', 'novecientos'),
  ivr('digits/hundred', 'cien'),
  // Thousands / millions / billions.
  ivr('digits/thousand', 'mil'),
  ivr('digits/million', 'millón'),
  ivr('digits/millions', 'millones'),
  ivr('digits/minus', 'menos'),
  // Ordinals.
  ivr('digits/h-1', 'primero'),
  ivr('digits/h-2', 'segundo'),
  ivr('digits/h-3', 'tercero'),
  ivr('digits/h-4', 'cuarto'),
  ivr('digits/h-5', 'quinto'),
  ivr('digits/h-6', 'sexto'),
  ivr('digits/h-7', 'séptimo'),
  ivr('digits/h-8', 'octavo'),
  ivr('digits/h-9', 'noveno'),
  ivr('digits/h-10', 'décimo'),
  ivr('digits/h-11', 'undécimo'),
  ivr('digits/h-12', 'duodécimo'),
  ivr('digits/h-13', 'décimo tercero'),
  ivr('digits/h-14', 'décimo cuarto'),
  ivr('digits/h-15', 'décimo quinto'),
  ivr('digits/h-16', 'décimo sexto'),
  ivr('digits/h-17', 'décimo séptimo'),
  ivr('digits/h-18', 'décimo octavo'),
  ivr('digits/h-19', 'décimo noveno'),
  ivr('digits/h-20', 'vigésimo'),
  ivr('digits/h-30', 'trigésimo'),
  ivr('digits/h-40', 'cuadragésimo'),
  ivr('digits/h-50', 'quincuagésimo'),
  ivr('digits/h-60', 'sexagésimo'),
  ivr('digits/h-70', 'septuagésimo'),
  ivr('digits/h-80', 'octogésimo'),
  ivr('digits/h-90', 'nonagésimo'),
  ivr('digits/h-hundred', 'centésimo'),
  ivr('digits/h-thousand', 'milésimo'),
  ivr('digits/h-million', 'millonésimo'),
  ivr('digits/h-billion', 'billonésimo'),
  // Time / dates.
  ivr('digits/a-m', 'a. m.'),
  ivr('digits/p-m', 'p. m.'),
  ivr('digits/at', 'a las'),
  ivr('digits/at_s', 'a la'),
  ivr('digits/oclock', 'en punto'),
  ivr('digits/afternoon', 'de la tarde'),
  ivr('digits/today', 'hoy'),
  ivr('digits/tomorrow', 'mañana'),
  ivr('digits/yesterday', 'ayer'),
  // Glue words.
  ivr('digits/and', 'y'),
  ivr('digits/oh', 'oh'),
  ivr('digits/es-de', 'de'),
  ivr('digits/es-el', 'el'),
  // Days of week (Sunday=0..Saturday=6).
  ivr('digits/day-0', 'domingo'),
  ivr('digits/day-1', 'lunes'),
  ivr('digits/day-2', 'martes'),
  ivr('digits/day-3', 'miércoles'),
  ivr('digits/day-4', 'jueves'),
  ivr('digits/day-5', 'viernes'),
  ivr('digits/day-6', 'sábado'),
  // Months (January=0..December=11).
  ivr('digits/mon-0', 'enero'),
  ivr('digits/mon-1', 'febrero'),
  ivr('digits/mon-2', 'marzo'),
  ivr('digits/mon-3', 'abril'),
  ivr('digits/mon-4', 'mayo'),
  ivr('digits/mon-5', 'junio'),
  ivr('digits/mon-6', 'julio'),
  ivr('digits/mon-7', 'agosto'),
  ivr('digits/mon-8', 'septiembre'),
  ivr('digits/mon-9', 'octubre'),
  ivr('digits/mon-10', 'noviembre'),
  ivr('digits/mon-11', 'diciembre'),
  // Currency / DTMF symbols.
  ivr('digits/dollars', 'pesos'),
  ivr('digits/pound', 'almohadilla'),
  ivr('digits/star', 'asterisco'),

  // ─────────────────────────────── dir-* ─────────────────────────────────
  ivr('dir-first', 'letras del primer nombre'),
  ivr('dir-firstlast',
    'letras del primer nombre o apellido de la persona'),
  ivr('dir-instr',
    'Si esta es la persona que usted busca, marque uno ahora. Si no, por favor marque el asterisco.'),
  ivr('dir-intro-fn',
    'Bienvenido al directorio. Por favor marque las tres primeras letras del nombre de la persona que busca, en su teclado. Use el siete para la Q y el nueve para la Z.'),
  ivr('dir-intro',
    'Bienvenido al directorio. Por favor marque las tres primeras letras del apellido de la persona que busca, en su teclado. Use el siete para la Q y el nueve para la Z.'),
  ivr('dir-last', 'letras del apellido de la persona'),
  ivr('dir-multi1', 'Presione'),
  ivr('dir-multi2', 'para'),
  ivr('dir-multi3', 'la extensión'),
  ivr('dir-multi9', 'Presione nueve para más resultados.'),
  ivr('dir-nomatch',
    'Nadie en el directorio corresponde a su búsqueda.'),
  ivr('dir-nomore',
    'No hay más entradas correspondientes en el directorio.'),
  ivr('dir-pls-enter', 'Por favor presione las primeras'),
  // dir-usingkeypad and dir-welcome are intentionally NOT here:
  // upstream ships them as empty/silent placeholders; we copy the
  // bytes verbatim from the upstream pack via passthrough.ts so the
  // tarball still contains the exact same file set.

  // ───────────────────────────── followme/* ──────────────────────────────
  ivr('followme/call-from', 'Llamada entrante de'),
  ivr('followme/no-recording', 'Usted tiene una llamada entrante.'),
  ivr('followme/options',
    'Presione uno para aceptar la llamada, o dos para rechazarla.'),
  ivr('followme/pls-hold-while-try',
    'Por favor espere mientras intento enlazar su llamada.'),
  ivr('followme/sorry',
    'Lo siento, pero no logré encontrar a la persona que busca.'),
  ivr('followme/status',
    'La persona a quien ha llamado no se encuentra en su escritorio. Intentaré localizarla por usted.'),

  // ─────────────────────────────── misc top-level ────────────────────────
  ivr('hello-world', '¡Hola mundo!'),
  ivr('hours', 'horas'),
  ivr('invalid',
    'Lo siento, esa es una extensión inválida. Por favor intente de nuevo.'),
  ivr('minutes', 'minutos'),
  ivr('seconds', 'segundos'),
  ivr('please-try-again', 'Por favor intente de nuevo.'),
  ivr('transfer',
    'Por favor espere mientras le comunico con esa extensión.'),

  // ─────────────────────────────── letters/* ─────────────────────────────
  ivr('letters/a', 'a'),
  ivr('letters/b', 'be'),
  ivr('letters/c', 'ce'),
  ivr('letters/d', 'de'),
  ivr('letters/e', 'e'),
  ivr('letters/f', 'efe'),
  ivr('letters/g', 'ge'),
  ivr('letters/h', 'hache'),
  ivr('letters/i', 'i'),
  ivr('letters/j', 'jota'),
  ivr('letters/k', 'ka'),
  ivr('letters/l', 'ele'),
  ivr('letters/m', 'eme'),
  ivr('letters/n', 'ene'),
  ivr('letters/o', 'o'),
  ivr('letters/p', 'pe'),
  ivr('letters/q', 'cu'),
  ivr('letters/r', 'erre'),
  ivr('letters/s', 'ese'),
  ivr('letters/t', 'te'),
  ivr('letters/u', 'u'),
  ivr('letters/v', 've'),
  ivr('letters/w', 'doble u'),
  ivr('letters/x', 'equis'),
  ivr('letters/y', 'i griega'),
  ivr('letters/z', 'zeta'),
  ivr('letters/at', 'arroba'),
  ivr('letters/dash', 'guion'),
  ivr('letters/dollar', 'signo de pesos'),
  ivr('letters/dot', 'punto'),
  ivr('letters/equals', 'igual'),
  ivr('letters/exclaimation-point', 'signo de exclamación'),
  ivr('letters/plus', 'más'),
  ivr('letters/slash', 'diagonal'),
  ivr('letters/space', 'espacio'),
  // Punctuation / ASCII symbols (paths kept identical to upstream so
  // dialplans like Read() that name them keep working).
  ivr('letters/ascii34', 'comillas'),
  ivr('letters/ascii36', 'signo de pesos'),
  ivr('letters/ascii37', 'porcentaje'),
  ivr('letters/ascii38', 'ampersand'),
  ivr('letters/ascii39', 'apóstrofo'),
  ivr('letters/ascii40', 'paréntesis izquierdo'),
  ivr('letters/ascii41', 'paréntesis derecho'),
  ivr('letters/ascii42', 'asterisco'),
  ivr('letters/ascii44', 'coma'),
  ivr('letters/ascii58', 'dos puntos'),
  ivr('letters/ascii59', 'punto y coma'),
  ivr('letters/ascii60', 'menor que'),
  ivr('letters/ascii62', 'mayor que'),
  ivr('letters/ascii63', 'signo de interrogación'),
  ivr('letters/ascii91', 'corchete izquierdo'),
  ivr('letters/ascii92', 'diagonal invertida'),
  ivr('letters/ascii93', 'corchete derecho'),
  ivr('letters/ascii94', 'acento circunflejo'),
  ivr('letters/ascii95', 'guion bajo'),
  ivr('letters/ascii96', 'acento grave'),
  ivr('letters/ascii123', 'llave izquierda'),
  ivr('letters/ascii124', 'barra vertical'),
  ivr('letters/ascii125', 'llave derecha'),
  ivr('letters/ascii126', 'tilde'),

  // ─────────────────────────────── pbx-* ─────────────────────────────────
  ivr('pbx-invalid',
    'Lo siento, esa es una extensión inválida. Por favor intente de nuevo.'),
  ivr('pbx-invalidpark',
    'Lo siento, no hay llamadas en esa extensión. Por favor intente de nuevo.'),
  ivr('pbx-parkingfailed',
    'El intento de estacionamiento de llamada ha fallado.'),
  ivr('pbx-transfer', 'Transferencia.'),

  // ───────────────────────────── phonetic/* ──────────────────────────────
  // Spanish ICAO/Telco phonetic alphabet, names anchored to common
  // hispanic first names so they stay clear under bad SIP audio.
  ivr('phonetic/a_p', 'Alfa'),
  ivr('phonetic/b_p', 'Bravo'),
  ivr('phonetic/c_p', 'Carlos'),
  ivr('phonetic/d_p', 'Delta'),
  ivr('phonetic/e_p', 'Eco'),
  ivr('phonetic/f_p', 'Francia'),
  ivr('phonetic/g_p', 'Gato'),
  ivr('phonetic/h_p', 'Hotel'),
  ivr('phonetic/i_p', 'India'),
  ivr('phonetic/j_p', 'Japón'),
  ivr('phonetic/k_p', 'Kilo'),
  ivr('phonetic/l_p', 'Lima'),
  ivr('phonetic/m_p', 'María'),
  ivr('phonetic/n_p', 'Nancy'),
  ivr('phonetic/o_p', 'Oscar'),
  ivr('phonetic/p_p', 'Papá'),
  ivr('phonetic/q_p', 'Queso'),
  ivr('phonetic/r_p', 'Romeo'),
  ivr('phonetic/s_p', 'Sandra'),
  ivr('phonetic/t_p', 'Tango'),
  ivr('phonetic/u_p', 'Urgente'),
  ivr('phonetic/v_p', 'Víctor'),
  ivr('phonetic/w_p', 'Whisky'),
  ivr('phonetic/x_p', 'X-Ray'),
  ivr('phonetic/y_p', 'Yankee'),
  ivr('phonetic/z_p', 'Zulú'),
  ivr('phonetic/9_p', 'noveno'),

  // ─────────────────────────────── priv-* / privacy-* ────────────────────
  ivr('priv-callee-options',
    'Marque uno si desea que esta persona se comunique con usted directamente ahora y en adelante. Marque dos si desea enviar a esta persona al buzón de voz ahora y en adelante. Marque tres para enviar a esta persona a las opciones de tortura ahora y en adelante. Marque cuatro para enviar a esta persona al menú de "no llamar" gentilmente ahora y en adelante. Marque cinco para que esta persona sea comunicada directamente con usted en el futuro, pero por esta vez mandarla al buzón de voz.'),
  ivr('priv-callpending', 'Tengo una persona esperando, que se llama'),
  ivr('priv-introsaved',
    'Gracias, por favor espere mientras intento comunicarle.'),
  ivr('priv-recordintro', 'Al tono, por favor indique su nombre.'),
  ivr('privacy-incorrect', 'Lo siento, ese número no es válido.'),
  ivr('privacy-prompt',
    'Por favor introduzca su número de teléfono empezando con la clave lada.'),
  ivr('privacy-thankyou', 'Muchas gracias.'),
  ivr('privacy-unident',
    'La persona que usted desea llamar no acepta llamadas no identificadas.'),

  // ─────────────────────────────── queue-* ───────────────────────────────
  ivr('queue-callswaiting', 'esperando por un representante.'),
  ivr('queue-holdtime', 'El tiempo de espera estimado es de'),
  ivr('queue-less-than', 'menos de'),
  ivr('queue-minute', 'minuto'),
  ivr('queue-minutes', 'minutos'),
  ivr('queue-periodic-announce',
    'Todos nuestros representantes se encuentran ocupados. Por favor espere y pronto le atenderemos.'),
  ivr('queue-quantity1', 'Por el momento hay más de'),
  ivr('queue-quantity2', 'llamadas en espera.'),
  ivr('queue-reporthold', 'Tiempo de espera'),
  ivr('queue-seconds', 'segundos'),
  ivr('queue-thankyou', 'Muchas gracias por su paciencia.'),
  ivr('queue-thereare', 'Usted es el cliente número'),
  ivr('queue-youarenext',
    'Su llamada es la primera en la línea y será atendida por el próximo representante disponible.'),

  // ─────────────────────────────── screen-* ──────────────────────────────
  ivr('screen-callee-options',
    'Usted tiene las siguientes opciones: marque uno si desea comunicarse inmediatamente con la llamada. Marque dos si desea enviar la persona al buzón de mensajes. Marque tres para enviar a esta persona a las opciones de tortura. Marque cuatro para enviar a esta persona a una opción cortés de "no llamar".'),

  // ─────────────────────────────── spy-* ─────────────────────────────────
  ivr('spy-agent', 'agente'),
  ivr('spy-console', 'consola'),
  ivr('spy-dahdi', 'D A H D I'),
  ivr('spy-h323', 'h 323'),
  ivr('spy-iax', 'I A X'),
  ivr('spy-iax2', 'I A X'),
  ivr('spy-jingle', 'jingle'),
  ivr('spy-local', 'local'),
  ivr('spy-mgcp', 'M G C P'),
  ivr('spy-misdn', 'M I S D N'),
  ivr('spy-mobile', 'Bluetooth'),
  ivr('spy-nbs', 'N B S'),
  ivr('spy-sip', 'SIP'),
  ivr('spy-skinny', 'skinny'),
  ivr('spy-unistim', 'Unistim'),
  ivr('spy-usbradio', 'radio U S B'),
  ivr('spy-zap', 'zap'),

  // ─────────────────────────────── ss-* / tt-* ───────────────────────────
  ivr('ss-noservice',
    'El número que usted ha marcado está fuera de servicio. Por favor verifique el número y vuelva a intentar.'),
  ivr('tt-allbusy',
    'Todos los representantes de la casa se encuentran ocupados asistiendo a otros vendedores por teléfono. Por favor espere y su llamada será atendida en el orden en que fue recibida.'),
  ivr('tt-monkeysintro', 'Han sido llevados por monos.'),
  ivr('tt-somethingwrong', 'Algo está terriblemente mal.'),
  ivr('tt-weasels',
    'Las comadrejas se han comido nuestro sistema telefónico.'),

  // ─────────────────────────────── vm-* ──────────────────────────────────
  // Folder names (capitalized in upstream).
  ivr('vm-Cust1', 'carpeta cinco'),
  ivr('vm-Cust2', 'carpeta seis'),
  ivr('vm-Cust3', 'carpeta siete'),
  ivr('vm-Cust4', 'carpeta ocho'),
  ivr('vm-Cust5', 'carpeta nueve'),
  ivr('vm-Family', 'familia'),
  ivr('vm-Friends', 'amigos'),
  ivr('vm-INBOX', 'nuevos'),
  ivr('vm-INBOXs', 'nuevo'),
  ivr('vm-Old', 'anteriores'),
  ivr('vm-Olds', 'anterior'),
  ivr('vm-Urgent', 'urgente'),
  ivr('vm-Work', 'trabajo'),
  // Voicemail prompts.
  ivr('vm-advopts', 'Marque tres para obtener las opciones avanzadas.'),
  ivr('vm-and', 'y'),
  ivr('vm-calldiffnum', 'Marque dos para llamar a otro número.'),
  ivr('vm-changeto', '¿Cambiar a qué carpeta?'),
  ivr('vm-delete', 'Marque siete para borrar el mensaje.'),
  ivr('vm-deleted', 'Mensaje borrado.'),
  ivr('vm-dialout',
    'Por favor espere mientras enlazo su llamada.'),
  ivr('vm-duration', 'La duración de este mensaje es de'),
  ivr('vm-enter-num-to-call',
    'Por favor marque el número que desea llamar.'),
  ivr('vm-extension', 'extensión'),
  ivr('vm-first', 'primer'),
  ivr('vm-for', 'para'),
  ivr('vm-forward-multiple',
    'Presione uno para mandar este mensaje, o dos para agregar otro destinatario.'),
  ivr('vm-forward',
    'Marque uno para teclear una extensión. Marque dos para obtener el directorio.'),
  ivr('vm-forwardoptions',
    'Marque uno para dejar pendiente un mensaje, o dos para enviar el mensaje sin espera.'),
  ivr('vm-from-extension', 'Mensaje de la extensión'),
  ivr('vm-from-phonenumber', 'Mensaje del número de teléfono'),
  ivr('vm-from', 'de'),
  ivr('vm-goodbye', 'Hasta pronto.'),
  ivr('vm-helpexit',
    'Marque el asterisco para obtener ayuda, o la tecla de almohadilla para salir.'),
  ivr('vm-incorrect-mailbox', 'Entrada incorrecta. ¿Buzón?'),
  ivr('vm-incorrect', 'Entrada incorrecta.'),
  ivr('vm-instructions',
    'Presione uno para escuchar sus mensajes. Presione la tecla de almohadilla para terminar en cualquier momento.'),
  ivr('vm-intro',
    'Por favor deje su mensaje después del tono. Al terminar, cuelgue o presione la tecla de almohadilla.'),
  ivr('vm-invalid-password',
    'La contraseña no cumple los requisitos mínimos para este correo de voz. Por favor intente de nuevo.'),
  ivr('vm-invalidpassword',
    'Contraseña incorrecta. Por favor, intente de nuevo.'),
  ivr('vm-isonphone', 'se encuentra ocupado.'),
  ivr('vm-isunavail', 'no está disponible.'),
  ivr('vm-last', 'último'),
  ivr('vm-leavemsg', 'Marque cinco para dejar mensaje.'),
  ivr('vm-login', 'Correo de voz. Ingrese su extensión.'),
  ivr('vm-mailboxfull',
    'Lo siento, pero el buzón de esta persona no puede aceptar más mensajes.'),
  ivr('vm-marked-nonurgent',
    'El estatus de urgencia ha sido desactivado para este mensaje.'),
  ivr('vm-marked-urgent',
    'Este mensaje ha sido marcado como urgente.'),
  ivr('vm-message', 'mensaje'),
  ivr('vm-messages', 'mensajes'),
  ivr('vm-minutes', 'minutos'),
  ivr('vm-mismatch',
    'Las contraseñas que usted tecleó no coinciden. Por favor intente de nuevo.'),
  ivr('vm-msginstruct',
    'Para escuchar el siguiente mensaje marque seis. Para repetir el mensaje marque cinco. Para escuchar el mensaje anterior marque cuatro. Para borrar o recuperar el mensaje marque cero. Para salir presione la tecla de almohadilla.'),
  ivr('vm-msgsaved', 'Su mensaje ha sido guardado.'),
  ivr('vm-newpassword',
    'Por favor ingrese su nueva contraseña seguida por la tecla de almohadilla.'),
  ivr('vm-newuser',
    'Bienvenido al correo de voz. Primero le guiaré a través del proceso de configuración.'),
  ivr('vm-next', 'Marque seis para escuchar el próximo mensaje.'),
  ivr('vm-no', 'no'),
  ivr('vm-nobodyavail',
    'En este momento nadie está disponible para responder a su llamada.'),
  ivr('vm-nobox',
    'Usted no puede responder a este mensaje porque el usuario no tiene buzón para mensajes.'),
  ivr('vm-nomore', 'No hay mensajes.'),
  ivr('vm-nonumber',
    'Lo siento, pero no sé quién ha enviado este mensaje.'),
  ivr('vm-num-i-have', 'El número que tengo es el'),
  ivr('vm-onefor-full', 'Presione uno para escuchar mensajes'),
  ivr('vm-onefor', 'Marque uno para'),
  ivr('vm-options',
    'Marque uno para grabar su mensaje de "no estoy disponible". Marque dos para grabar su mensaje de "ocupado". Marque tres para grabar su nombre. Marque cuatro para grabar su mensaje de bienvenida temporal. Marque cinco para cambiar su contraseña. Marque el asterisco para volver a las opciones principales.'),
  ivr('vm-opts-full',
    'Presione dos para mensajes guardados en otras carpetas. Presione tres para grabar un mensaje a otra persona. Presione cero para opciones de saludo y contraseña.'),
  ivr('vm-opts',
    'Marque dos para cambiar de carpeta. Tres para opciones avanzadas. O cero para opciones del correo.'),
  ivr('vm-passchanged', 'Sus contraseñas han sido cambiadas.'),
  ivr('vm-password', 'contraseña'),
  ivr('vm-pls-try-again', 'Por favor intente de nuevo.'),
  ivr('vm-press', 'marque'),
  ivr('vm-prev', 'Marque cuatro para el mensaje previo.'),
  ivr('vm-reachoper', 'Marque cero para hablar con la operadora.'),
  ivr('vm-rec-busy',
    'Después del tono grabe su mensaje de "ocupado" y presione la tecla de almohadilla.'),
  ivr('vm-rec-name',
    'Después del tono diga su nombre y presione la tecla de almohadilla.'),
  ivr('vm-rec-temp',
    'Después del tono grabe su mensaje temporal y presione la tecla de almohadilla.'),
  ivr('vm-rec-unv',
    'Después del tono grabe su mensaje de "no disponible" y presione la tecla de almohadilla.'),
  ivr('vm-received', 'recibido'),
  ivr('vm-record-prepend',
    'Al escuchar el tono, por favor grabe la introducción para el mensaje reenviado. Al terminar, presione la tecla de almohadilla.'),
  ivr('vm-reenterpassword',
    'Por favor ingrese su contraseña de nuevo y presione la tecla de almohadilla.'),
  ivr('vm-repeat', 'Marque cinco para repetir el mensaje.'),
  ivr('vm-review-nonurgent',
    'Presione cuatro para desactivar el estatus de urgencia del mensaje.'),
  ivr('vm-review-urgent',
    'Presione cuatro para marcar este mensaje como urgente.'),
  ivr('vm-review',
    'Marque uno para aceptar esta grabación. Dos para escucharla. Tres para volver a grabar su mensaje.'),
  ivr('vm-saved', 'guardado'),
  ivr('vm-savedto', 'guardado en'),
  ivr('vm-savefolder', '¿En qué carpeta desea guardar el mensaje?'),
  ivr('vm-savemessage', 'o nueve para guardar este mensaje'),
  ivr('vm-saveoper',
    'Marque uno para aceptar esta grabación. De lo contrario, por favor espere en la línea.'),
  ivr('vm-sorry', 'Lo siento, no comprendí su respuesta.'),
  ivr('vm-star-cancel', 'Marque el asterisco para cancelar.'),
  ivr('vm-starmain',
    'Marque el asterisco para regresar a las opciones principales.'),
  ivr('vm-tempgreetactive',
    'Su saludo temporal está actualmente en uso.'),
  ivr('vm-tempgreeting',
    'Marque uno para grabar su saludo temporal.'),
  ivr('vm-tempgreeting2',
    'Marque uno para grabar su saludo temporal, o dos para borrarlo.'),
  ivr('vm-tempremoved', 'Su saludo temporal ha sido borrado.'),
  ivr('vm-then-pound', 'luego presione la tecla de almohadilla'),
  ivr('vm-theperson', 'La persona en la extensión'),
  ivr('vm-tmpexists',
    'Hay un saludo temporal en lugar del saludo estándar.'),
  ivr('vm-tocallback',
    'Marque dos para llamar a la persona que ha enviado este mensaje.'),
  ivr('vm-tocallnum', 'Marque uno para llamar a este número.'),
  ivr('vm-tocancel', 'o la tecla de almohadilla para cancelar.'),
  ivr('vm-tocancelmsg',
    'Marque el asterisco para cancelar este mensaje.'),
  ivr('vm-toenternumber', 'Marque uno para ingresar un número.'),
  ivr('vm-toforward',
    'Marque ocho para enviar este mensaje a otro usuario.'),
  ivr('vm-tohearenv',
    'Marque tres para escuchar las propiedades de este mensaje.'),
  ivr('vm-tomakecall',
    'Marque cuatro para hacer una llamada al exterior.'),
  ivr('vm-tooshort', 'Su mensaje es muy corto.'),
  ivr('vm-toreply', 'Marque uno para enviar una respuesta.'),
  ivr('vm-torerecord',
    'Marque tres para volver a grabar su mensaje.'),
  ivr('vm-undelete', 'Marque siete para recuperar el mensaje.'),
  ivr('vm-undeleted', 'Mensaje recuperado.'),
  ivr('vm-unknown-caller', 'De una persona no identificada.'),
  ivr('vm-whichbox',
    'Para dejar un mensaje, por favor ingrese un número de buzón.'),
  ivr('vm-youhave', 'Usted tiene'),
  ivr('vm-youhaveno', 'Usted no tiene'),
];

void tail; // (kept for future per-item tags overriding the default style)
